"""Build domain-only Surge rules from reviewed, local sources; never read profiles."""
from pathlib import Path
import hashlib, json, re, sys
ROOT = Path(__file__).resolve().parents[1]
DOMAIN = re.compile(r'(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z][a-z0-9-]*$')
def lines(path):
    return [l.strip() for l in path.read_text().splitlines() if l.strip() and not l.startswith('#')]
def validate(items):
    for line in items:
        fields = line.split(',')
        assert len(fields) == 2 and fields[0] in ('DOMAIN', 'DOMAIN-SUFFIX'), line
        assert DOMAIN.fullmatch(fields[1]), line
        assert not fields[1].endswith(('.local', '.internal', '.ts.net')), line
    return sorted(set(items))
meta = json.loads((ROOT/'upstream/provenance.json').read_text())
assert hashlib.sha256((ROOT/'upstream/China_Domain.list').read_bytes()).hexdigest() == meta['sha256']
china = [('DOMAIN-SUFFIX,'+d[1:]) if d.startswith('.') else ('DOMAIN,'+d) for d in lines(ROOT/'upstream/China_Domain.list')]
outputs = {
    'ai-services': lines(ROOT/'source/ai-services.list'),
    'model-downloads': lines(ROOT/'source/model-downloads.list'),
    'china-direct': china + lines(ROOT/'source/china-additions.list'),
}
for name, items in outputs.items():
    body = '# Generated by scripts/build.py; domain rules only, no policies or credentials.\n' + '\n'.join(validate(items)) + '\n'
    path = ROOT/'rules'/f'{name}.list'
    if '--check' in sys.argv:
        assert path.read_text() == body, f'Rebuild {name}'
    else:
        path.write_text(body)
    print(name, len(set(items)))
def matches(name, domain):
    return any(domain == v or (k == 'DOMAIN-SUFFIX' and domain.endswith('.'+v)) for k,v in (x.split(',') for x in outputs[name]))
for domain in ['chatgpt.com', 'api.openai.com', 'claude.ai', 'gemini.google.com', 'copilot.microsoft.com', 'api.x.ai', 'api.cursor.com']:
    assert matches('ai-services', domain), domain
for domain in ['qq.com', 'baidu.com', 'qpic.cn', 'qlogo.cn', 'sinaimg.cn', 'wps.cn', 'kdocs.cn', '12306.cn', 'volcengine.com']:
    assert matches('china-direct', domain), domain
for domain in ['chatgpt.com', 'copilot.microsoft.com', 'foreign.microsoft.example', 'example.sora.example']:
    assert not matches('china-direct', domain), domain
for domain in ['huggingface.co', 'registry.ollama.ai', 'pytorch.org']:
    assert matches('model-downloads', domain), domain
print('Format, provenance, generated-file and routing-boundary checks passed.')
